export type Listing = {
  slug: string;
  price: string;
  priceNum: number;
  priceJPY: string;
  name: string;
  city: string;
  prefecture: string;
  region: string;
  beds: number;
  size: string;
  built: string;
  parking: string;
  notes: string;
  isPremium: boolean;
  contact?: string;
  tags: string[];
  images: string[];
};

const CDN = "https://cdn.prod.website-files.com/6789dd1a798234106f5e33b7/";

export const listings: Listing[] = [
  {
    slug: "joetsu-niigata-1000yen",
    price: "$7", priceNum: 7, priceJPY: "¥1,000",
    name: "A Rare 1,000-Yen Countryside Home in Joetsu",
    city: "Joetsu", prefecture: "Niigata", region: "Chubu",
    beds: 10, size: "1,367", built: "1974", parking: "1 spot",
    notes: "Extremely low price; 10-room wooden house on 150-tsubo lot. Ideal for DIY renovation. Land value likely exceeds asking price.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["renovation-project", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "sasebo-nagasaki-68",
    price: "$68", priceNum: 68, priceJPY: "¥80K",
    name: "Traditional Home in Sasebo",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 4, size: "649", built: "Est. 1960s", parking: "0 spots",
    notes: "Traditional Japanese home in quiet residential area. Renovation required but price is minimal. Scenic coastal region.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["renovation-project", "coastal", "nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "hakodate-hokkaido-69",
    price: "$69", priceNum: 69, priceJPY: "¥80K",
    name: "3LDK Home in Hakodate",
    city: "Hakodate", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "682", built: "1969", parking: "0 spots",
    notes: "Quiet residential neighborhood in historic port city. Classic Japanese layout with renovation potential.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["renovation-project", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "000 sq ft on large lot near Sunagawa City. Shops and schools nearby. Rare entry-level price for Hokkaido.",
    price: "$640", priceNum: 640, priceJPY: "¥750K",
    name: "Spacious 3LDK on Large Lot — Sorachi District",
    city: "Sunagawa", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "1,989", built: "1961", parking: "1 spot",
    notes: "Nearly 2",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/sorachi-hokkaido-640",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "otaru-hokkaido-1281",
    price: "$1281", priceNum: 1281, priceJPY: "¥1.5M",
    name: "3LDK Home With Garden & Parking in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "1,024", built: "1966", parking: "1 spot",
    notes: "Peaceful coastal living in Hokkaido's beloved Otaru. Convenience store within 10 min walk. Garden included. Historic canal and glass workshops.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["coastal", "garden", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "iwamizawa-hokkaido",
    price: "$1281", priceNum: 1281, priceJPY: "¥1.5M",
    name: "Two-Story Home in Iwamizawa, Hokkaido",
    city: "Iwamizawa", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "1,024", built: "1966", parking: "1 spot",
    notes: "Peaceful Hokkaido living between Sapporo and Asahikawa. Convenience store within walking distance. Garden included.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["garden", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "muroran-hokkaido-1921",
    price: "$1921", priceNum: 1921, priceJPY: "¥2.3M",
    name: "Wooden Home in Coastal Muroran",
    city: "Muroran", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "811", built: "1976", parking: "0 spots",
    notes: "Diamond-in-rough on Hokkaido coast. Industrial port city with dramatic cliff scenery and island access. Renovation required.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["renovation-project", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "seiyo-ehime-2036",
    price: "$2036", priceNum: 2036, priceJPY: "¥2.4M",
    name: "Charming Home in Seiyo, Ehime",
    city: "Seiyo", prefecture: "Ehime", region: "Shikoku",
    beds: 2, size: "676", built: "1975", parking: "0 spots",
    notes: "Traditional 4DK with tatami rooms and shoji doors. Quiet residential area in western Ehime. Renovation potential throughout.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["renovation-project", "ehime"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tane-shiga-4dk",
    price: "$2200", priceNum: 2200, priceJPY: "¥2.6M",
    name: "4DK Home in Tane, Higashiomi",
    city: "Tane", prefecture: "Shiga", region: "Kansai",
    beds: 4, size: "1,158", built: "1975", parking: "2 spots",
    notes: "Spacious wooden interiors with tatami rooms near Lake Biwa. 2 parking spots. Ideal for rural living in scenic area.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["shiga"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "nagasaki-city-traditional-2250",
    price: "$2250", priceNum: 2250, priceJPY: "¥2.7M",
    name: "Traditional Akiya in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 4, size: "598", built: "1968", parking: "0 spots",
    notes: "Traditional akiya with tatami rooms and wood interiors. Walking distance to local amenities in culturally rich Nagasaki.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "000. Coastal city known for harbor and island scenery.",
    price: "$2695", priceNum: 2695, priceJPY: "¥3.2M",
    name: "Historic Akiya in Sasebo — Built 1900",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 3, size: "637", built: "1900", parking: "0 spots",
    notes: "Over 125 years old. A piece of Japanese history for under $3",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/sasebo-nagasaki-1900",
    tags: ["nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "joetsu-niigata-5bed-v2",
    price: "$2700", priceNum: 2700, priceJPY: "¥3.2M",
    name: "Spacious 5-Bedroom Akiya in Joetsu",
    city: "Joetsu", prefecture: "Niigata", region: "Chubu",
    beds: 5, size: "1,274", built: "1978", parking: "1 spot",
    notes: "Tatami rooms and traditional charm near mountains and sea. Gateway to Myoko and Hakuba ski resorts.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["coastal", "mountain", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "200 sq ft for under $3",
    price: "$2957", priceNum: 2957, priceJPY: "¥3.5M",
    name: "6DK Home in Kamijo, Kashiwazaki",
    city: "Kashiwazaki", prefecture: "Niigata", region: "Chubu",
    beds: 6, size: "2,277", built: "1936", parking: "1 spot",
    notes: "90-year-old wooden Japanese home with garden. Over 2",
    isPremium: false, contact: "000. Sea of Japan coast with bullet train access to Tokyo.",
    tags: ["garden", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "500. Toyama ranked #1 in Japan for quality of life. Traditional Japanese countryside layout.",
    price: "$3427", priceNum: 3427, priceJPY: "¥4M",
    name: "7-Bedroom Village Escape in Imizu",
    city: "Imizu", prefecture: "Toyama", region: "Chubu",
    beds: 7, size: "1,275", built: "1971", parking: "0 spots",
    notes: "7 bedrooms for under $3",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/imizu-toyama-3427",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "nagasaki-hillside-4dk",
    price: "$3700", priceNum: 3700, priceJPY: "¥4.4M",
    name: "Hillside Hideaway in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 4, size: "1,139", built: "1967", parking: "0 spots",
    notes: "4DK with mountain views in Nagasaki City — historically rich city with stunning harbor views.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["mountain", "nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "sea",
    price: "$4042", priceNum: 4042, priceJPY: "¥4.8M",
    name: "Spacious Akiya in Joetsu",
    city: "Joetsu", prefecture: "Niigata", region: "Chubu",
    beds: 5, size: "1,274", built: "1978", parking: "0 spots",
    notes: "Tatami rooms and traditional Japanese charm. Joetsu offers mountains",
    isPremium: false, contact: "and excellent skiing — gateway to ski resorts.",
    tags: ["mountain", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "000. Harbor dotted with over 200 beautiful islands.",
    price: "$4200", priceNum: 4200, priceJPY: "¥5M",
    name: "6DK Home with Bay Views in Sasebo",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 6, size: "1,303", built: "1967", parking: "0 spots",
    notes: "Bay views and coastal charm in Sasebo for under $5",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/sasebo-bay-views-6dk",
    tags: ["coastal", "nagasaki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "000 sq ft for under $5",
    price: "$4400", priceNum: 4400, priceJPY: "¥5.2M",
    name: "7-Bedroom Akiya in Kashiwazaki",
    city: "Kashiwazaki", prefecture: "Niigata", region: "Chubu",
    beds: 7, size: "3,195", built: "1974", parking: "2 spots",
    notes: "Over 3",
    isPremium: false, contact: "000 near Sea of Japan. 7 bedrooms. Classic Japanese coastal living.",
    tags: ["niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "ebino-miyazaki-4560",
    price: "$4560", priceNum: 4560, priceJPY: "¥5.4M",
    name: "Ebino Hillside Hideaway",
    city: "Ebino", prefecture: "Miyazaki", region: "Kyushu",
    beds: 3, size: "896", built: "1975", parking: "0 spots",
    notes: "Surrounded by nature with large yard and mountain views. Highland city near Kirishima National Park.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["mountain", "miyazaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "otaru-hokkaido-5122",
    price: "$5122", priceNum: 5122, priceJPY: "¥6M",
    name: "Classic 4LDK Home in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,208", built: "Est. 1960s", parking: "1 spot",
    notes: "Quiet residential neighborhood in beloved Otaru. Famous for snow canal and seafood. Top tourist destination and highly livable.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["coastal", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "otaru-hokkaido-budget-4ldk",
    price: "$5122", priceNum: 5122, priceJPY: "¥6M",
    name: "Budget 4LDK House in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "875", built: "1964", parking: "0 spots",
    notes: "Rare affordable entry into Hokkaido real estate in charming Otaru. Potential as guesthouse or rental.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "000 available from local government. Note: major floor and plumbing repairs needed.",
    price: "$6332", priceNum: 6332, priceJPY: "¥1M",
    name: "5DK Two-Story House in Kurayoshi",
    city: "Kurayoshi", prefecture: "Tottori", region: "Japan",
    beds: 5, size: "1,119", built: "1983", parking: "0 spots",
    notes: "Includes storehouse. Acquisition subsidy up to ¥400",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/kurayoshi-tottori-6332",
    tags: ["tottori", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "takikawa-hokkaido-6338",
    price: "$6338", priceNum: 6338, priceJPY: "¥7.5M",
    name: "Two-Story Home Near Takikawa Station",
    city: "Takikawa", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,025", built: "1973", parking: "0 spots",
    notes: "Walk to train station. Full ownership. Known for glider aviation and rapeseed fields. Easy access to Sapporo by train.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "minamisoma-fukushima",
    price: "$6500", priceNum: 6500, priceJPY: "¥7.6M",
    name: "6DK Home in Minamisoma, Fukushima",
    city: "Minamisoma", prefecture: "Fukushima", region: "Tohoku",
    beds: 6, size: "1,429", built: "1980", parking: "2 spots",
    notes: "2-story wooden house 2km from Haranomachi Station. 6 bedrooms with sunlight and parking. Fukushima coast.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["fukushima", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "000 sq ft for under $7",
    price: "$6602", priceNum: 6602, priceJPY: "¥7.8M",
    name: "Cozy Akiya in Kashiwazaki — 3,195 sq ft",
    city: "Kashiwazaki", prefecture: "Niigata", region: "Chubu",
    beds: 7, size: "3,195", built: "1974", parking: "2 spots",
    notes: "Over 3",
    isPremium: false, contact: "000. 7 bedrooms. Near Sea of Japan. One of best value-per-sqft listings.",
    tags: ["niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "matsue-garden-akiya",
    price: "$6900", priceNum: 6900, priceJPY: "¥8.1M",
    name: "Matsue City Garden-View Akiya",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 5, size: "973", built: "1970", parking: "1 spot",
    notes: "5DK akiya with yard and detached outbuilding in Matsue. Renovation-ready in Japan's charming water city.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["renovation-project", "shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "saijo-ehime-7590",
    price: "$7590", priceNum: 7590, priceJPY: "¥8.9M",
    name: "6DK Home in Saijo City",
    city: "Saijo", prefecture: "Ehime", region: "Shikoku",
    beds: 6, size: "1,919", built: "1991", parking: "1 spot",
    notes: "One of newer builds (1991). Spacious 6-bedroom layout with garden. Known for pure groundwater and traditional festivals.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["garden", "ehime", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "755 sqft of classic Japanese countryside living.",
    price: "$7800", priceNum: 7800, priceJPY: "¥9.2M",
    name: "6DK Two-Story Home in Kosaka, Kunimi-machi",
    city: "Kunimi", prefecture: "Fukushima", region: "Tohoku",
    beds: 6, size: "1,755", built: "1979", parking: "1 spot",
    notes: "Sunny veranda and spacious garden with privacy near expressway. 1",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/kosaka-fukushima-6dk",
    tags: ["garden", "fukushima", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "600 sqft lot with parking. Japan's City of Water with preserved castle.",
    price: "$8400", priceNum: 8400, priceJPY: "¥9.8M",
    name: "Traditional 6DK Home in Akikacho, Matsue",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 6, size: "1,432", built: "1970", parking: "3 spots",
    notes: "3-min walk to Akikacho Station. Large 4",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/akikacho-matsue-shimane",
    tags: ["shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "izumo-shimane-3dk",
    price: "$8450", priceNum: 8450, priceJPY: "¥9.9M",
    name: "Cozy 3DK Countryside Home in Izumo",
    city: "Izumo", prefecture: "Shimane", region: "Chugoku",
    beds: 3, size: "1,066", built: "1983", parking: "0 spots",
    notes: "Single-story home near sea in Izumo City with garden. Home to one of Japan's most sacred Shinto shrines.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["coastal", "garden", "shimane"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "hiking",
    price: "$9375", priceNum: 9375, priceJPY: "¥11M",
    name: "4-Bedroom Akiya Near Scenic Trails in Nagano",
    city: "Nagano", prefecture: "Nagano", region: "Japan",
    beds: 4, size: "1,149", built: "Est. 1970s", parking: "0 spots",
    notes: "Unique akiya surrounded by scenic trails. Japan Alps country with skiing",
    isPremium: false, contact: "and onsen nearby.",
    tags: ["nagano"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "nagano-7bed-minamimaki",
    price: "$9375", priceNum: 9375, priceJPY: "¥11M",
    name: "Tranquil 7-Bedroom Akiya in Nagano",
    city: "Minamimaki", prefecture: "Nagano", region: "Japan",
    beds: 7, size: "1,285", built: "1970", parking: "0 spots",
    notes: "7 bedrooms in serene Minamimaki Village. Quiet countryside living in heart of Japan Alps.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["nagano", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "000. 20 minutes from central Kyoto by train. Garden and parking. Budget-friendly Kyoto entry.",
    price: "$9827", priceNum: 9827, priceJPY: "¥11.6M",
    name: "4DK Home Near Kyoto in Kameoka City",
    city: "Kameoka", prefecture: "Kyoto", region: "Kansai",
    beds: 4, size: "810", built: "1977", parking: "3 spots",
    notes: "Kyoto Prefecture for under $10",
    isPremium: false, contact: "https://www.cheapakiya.com/listings/kameoka-kyoto-9827",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "keihoku-kyoto-2dk",
    price: "$9827", priceNum: 9827, priceJPY: "¥11.6M",
    name: "2DK Home in Keihoku Shuzan-cho, Kyoto",
    city: "Kyoto", prefecture: "Kyoto", region: "Kansai",
    beds: 2, size: "710", built: "1988", parking: "0 spots",
    notes: "Tucked in Kyoto City's serene Keihoku area. Single-story wooden home. Tranquility and affordability within Kyoto city limits.",
    isPremium: false, contact: "info@cheapakiya.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-3ldk-home-on-a-large-lot-in-sorachi-district",
    price: "$640", priceNum: 640, priceJPY: "¥750K",
    name: "Spacious 3LDK Home on a Large Lot in Sorachi District",
    city: "Kamisunagawachō", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "1,989", built: "1961", parking: "1 spot",
    notes: "Affordable entry-level Hokkaido property. Large lot with quiet residential feel near Sunagawa City. Easy access to shops and schools.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "classic-4ldk-home-in-otaru",
    price: "$5122", priceNum: 5122, priceJPY: "¥6M",
    name: "Classic 4LDK Home in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,208", built: "1900", parking: "1 spot",
    notes: "Peaceful Hokkaido living in quiet residential neighborhood. Close to city conveniences and local amenities.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "budget-4ldk-house-in-otaru",
    price: "$5122", priceNum: 5122, priceJPY: "¥6M",
    name: "Budget 4LDK House in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "875", built: "1964", parking: "0 spots",
    notes: "Rare affordable entry point into Hokkaido real estate. Potential for renovation into home or rental property with character.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "wooden-home-in-coastal-muroran",
    price: "$1921", priceNum: 1921, priceJPY: "¥2.3M",
    name: "Wooden Home in Coastal Muroran",
    city: "Muroran", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "811", built: "1976", parking: "0 spots",
    notes: "Diamond-in-the-rough coastal akiya market property. Traditional wooden home with renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "coastal", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "two-story-home-in-iwamizawa-hokkaido",
    price: "$5752", priceNum: 5752, priceJPY: "¥6.8M",
    name: "Two-Story Home in Iwamizawa, Hokkaido",
    city: "Iwamizawa", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,073", built: "1975", parking: "2 spots",
    notes: "Spacious two-story home with parking. Hokkaido countryside living near local amenities.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "3ldk-home-with-garden-parking-in-otaru",
    price: "$1281", priceNum: 1281, priceJPY: "¥1.5M",
    name: "3LDK Home With Garden & Parking in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "1,024", built: "1966", parking: "1 spot",
    notes: "Charming Sakura neighborhood property. Quiet area with easy access to shops. Garden and parking included.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "affordable-two-story-home-near-takikawa-station",
    price: "$6338", priceNum: 6338, priceJPY: "¥7.5M",
    name: "Affordable Two-Story Home Near Takikawa Station",
    city: "Takikawa", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,025", built: "1973", parking: "0 spots",
    notes: "Walk to train station. Full ownership. Two-story home with convenience and transit access.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "3dk-single-story-home-in-kitahara",
    price: "$6500", priceNum: 6500, priceJPY: "¥7.6M",
    name: "3DK Single-Story Home in Kitahara",
    city: "Kitahara", prefecture: "Fukushima", region: "Tohoku",
    beds: 3, size: "NA", built: "1955", parking: "1 spot",
    notes: "Budget-friendly akiya in Fukushima. Single-story traditional layout with renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "fukushima"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "6dk-home-in-kamijo-kashiwazaki-city-niigata",
    price: "$2957", priceNum: 2957, priceJPY: "¥3.5M",
    name: "6DK Home in Kamijo, Kashiwazaki City, Niigata",
    city: "Kashiwazaki", prefecture: "Niigata", region: "Chubu",
    beds: 6, size: "2,277", built: "1936", parking: "1 spot",
    notes: "Spacious wooden home with garden. Historic 1936 build. Significant renovation potential on large lot.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "garden", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-home-in-seiyo-ehime",
    price: "$2036", priceNum: 2036, priceJPY: "¥2.4M",
    name: "Charming Home in Seiyo, Ehime",
    city: "Seiyo", prefecture: "Ehime", region: "Shikoku",
    beds: 2, size: "676", built: "1975", parking: "0 spots",
    notes: "Traditional 4DK with tatami rooms and shoji doors. Quiet residential area in western Ehime. Renovation potential throughout.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "ehime"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-home-in-sasebo-nagasaki",
    price: "$68", priceNum: 68, priceJPY: "¥80K",
    name: "Traditional Home in Sasebo, Nagasaki",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 4, size: "649", built: "Unknown", parking: "0 spots",
    notes: "Traditional 4DK with tatami rooms and renovation potential in quiet residential neighborhood.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "3ldk-home-in-hakodate-hokkaido",
    price: "$69", priceNum: 69, priceJPY: "¥80K",
    name: "3LDK Home in Hakodate, Hokkaido",
    city: "Hakodate", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "682", built: "1969", parking: "0 spots",
    notes: "Charming akiya in quiet residential area. Ideal for renovation with traditional features and convenient access to local amenities.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "5k-home-in-nagasaki-city",
    price: "$6651", priceNum: 6651, priceJPY: "¥7.8M",
    name: "5K Home in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 5, size: "962", built: "1967", parking: "0 spots",
    notes: "Traditional 5DK with tatami rooms and shoji doors. Renovation potential in quiet residential neighborhood.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "nagasaki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "6dk-two-story-home-in-kosaka-kunimi-machi",
    price: "$11700", priceNum: 11700, priceJPY: "¥1.37M",
    name: "6DK Two-Story Home in Kosaka, Kunimi-machi",
    city: "Kunimi", prefecture: "Fukushima", region: "Tohoku",
    beds: 6, size: "1,755", built: "1979", parking: "1 spot",
    notes: "Sunny veranda with spacious garden and privacy near expressway. Classic Japanese countryside living.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "fukushima", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "cozy-3dk-countryside-home-in-koryocho-oike",
    price: "$16900", priceNum: 16900, priceJPY: "¥2M",
    name: "Cozy 3DK Countryside Home in Koryocho Oike",
    city: "Izumo", prefecture: "Shimane", region: "Chugoku",
    beds: 3, size: "1,066", built: "1983", parking: "0 spots",
    notes: "Single-story home near sea with garden and countryside charm. Izumo is known for cultural significance.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["coastal", "garden", "shimane"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-6dk-home-in-akikacho",
    price: "$12670", priceNum: 12670, priceJPY: "¥14.9M",
    name: "Traditional 6DK Home in Akikacho",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 6, size: "1,432", built: "1970", parking: "3 spots",
    notes: "Charming wooden home near Akikacho Station. Large lot with parking for 3+. Quiet and sunny.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "used-detached-house-in-takamicho",
    price: "$12900", priceNum: 12900, priceJPY: "¥1.98M",
    name: "Used Detached House in Takamicho",
    city: "Minamisoma", prefecture: "Fukushima", region: "Tohoku",
    beds: 6, size: "1,429", built: "1980", parking: "2 spots",
    notes: "2-story wooden house 2km from Haranomachi Station with sunlight and parking on Fukushima coast.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["fukushima", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "4dk-home-in-tane",
    price: "$3312", priceNum: 3312, priceJPY: "¥3.9M",
    name: "4DK Home in Tane",
    city: "Tane", prefecture: "Ehime", region: "Shikoku",
    beds: 4, size: "1,158", built: "1975", parking: "2 spots",
    notes: "Spacious layout with wooden interiors and renovation potential. Ideal for rural living in Japan.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "ehime"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-akiya-in-joetsu-niigata",
    price: "$2700", priceNum: 2700, priceJPY: "¥3.2M",
    name: "Spacious 5-Bedroom Akiya in Joetsu",
    city: "Joetsu", prefecture: "Niigata", region: "Chubu",
    beds: 5, size: "1,274", built: "1978", parking: "1 spot",
    notes: "Tatami rooms and traditional charm near mountains and sea. Gateway to Myoko and Hakuba ski resorts.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["coastal", "mountain", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "ebino-hillside-hideaway",
    price: "$4560", priceNum: 4560, priceJPY: "¥5.3M",
    name: "Ebino Hillside Hideaway",
    city: "Ebino", prefecture: "Miyazaki", region: "Kyushu",
    beds: 3, size: "896", built: "1975", parking: "1 spot",
    notes: "5DK surrounded by nature with large yard and mountain views near Kirishima National Park.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "miyazaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "hillside-hideaway-in-nagasaki-city",
    price: "$5551", priceNum: 5551, priceJPY: "¥6.5M",
    name: "Hillside Hideaway in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 5, size: "1,139", built: "1967", parking: "0 spots",
    notes: "4DK traditional home with mountain views and renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "mountain", "nagasaki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "matsue-city-garden-view-akiya",
    price: "$10410", priceNum: 10410, priceJPY: "¥12M",
    name: "Matsue City Garden-View Akiya",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 5, size: "973", built: "1970", parking: "0 spots",
    notes: "5DK akiya with yard and detached structure in charming water city.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "shimane-starter-akiya-in-matsue-city",
    price: "$17350", priceNum: 17350, priceJPY: "¥20M",
    name: "Shimane Starter Akiya in Matsue City",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 6, size: "1,200", built: "1976", parking: "0 spots",
    notes: "6K affordable fixer-upper in scenic Matsue.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "6dk-home-in-saijo-city-ehime",
    price: "$7590", priceNum: 7590, priceJPY: "¥8.9M",
    name: "6DK Home in Saijo City",
    city: "Saijo", prefecture: "Ehime", region: "Shikoku",
    beds: 6, size: "1,919", built: "1991", parking: "1 spot",
    notes: "One of newer builds (1991). Spacious 6-bedroom layout with garden. Known for pure groundwater and traditional festivals.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "ehime", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-4-bedroom-akiya-retreat-in-shiomigaoka-4-chome",
    price: "$32000", priceNum: 32000, priceJPY: "¥37M",
    name: "Traditional 4-Bedroom Akiya Retreat in Shiomigaoka 4-chome",
    city: "Shiomigaoka", prefecture: "Ibaraki", region: "Kanto",
    beds: 4, size: "891", built: "1980", parking: "1 spot",
    notes: "4DK traditional akiya with renovation potential.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-2-bedroom-countryside-hideaway-in-kumiage",
    price: "$20000", priceNum: 20000, priceJPY: "¥23M",
    name: "Spacious 2-Bedroom Countryside Hideaway in Kumiage",
    city: "Kumiage", prefecture: "Ibaraki", region: "Kanto",
    beds: 2, size: "538", built: "1987", parking: "1 spot",
    notes: "2-bedroom rural property with countryside charm.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-4-bedroom-country-home-in-sunazawacho",
    price: "$13333", priceNum: 13333, priceJPY: "¥15M",
    name: "Tranquil 4-Bedroom Country Home in Sunazawacho",
    city: "Sunazawacho", prefecture: "Ibaraki", region: "Kanto",
    beds: 4, size: "980", built: "1993", parking: "1 spot",
    notes: "4K country property with modern updates.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-home-in-nagasaki-city",
    price: "$3370", priceNum: 3370, priceJPY: "¥3.9M",
    name: "Traditional Home in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 4, size: "598", built: "1968", parking: "0 spots",
    notes: "4DK traditional akiya with tatami rooms in culturally rich city.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "akiya-in-sasebo-nagasaki",
    price: "$2695", priceNum: 2695, priceJPY: "¥3.2M",
    name: "Akiya in Sasebo, Nagasaki",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 3, size: "637", built: "1900", parking: "0 spots",
    notes: "3-bedroom affordable akiya with charm and renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "affordable-6dk-home-with-bay-views-in-sasebo-city",
    price: "$6245", priceNum: 6245, priceJPY: "¥7.3M",
    name: "Affordable 6DK Home with Bay Views in Sasebo City",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 6, size: "1,303", built: "1967", parking: "0 spots",
    notes: "6DK akiya with coastal bay views and renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "coastal", "nagasaki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-7-bedroom-cultural-gem-in-tate",
    price: "$6854", priceNum: 6854, priceJPY: "¥8M",
    name: "Spacious 7-Bedroom Cultural Gem in Tate",
    city: "Tate", prefecture: "Toyama", region: "Chubu",
    beds: 7, size: "1,698", built: "1969", parking: "1 spot",
    notes: "Spacious 7DK traditional home in rural Toyama.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "cozy-akiya-in-kashiwazaki-niigata",
    price: "$6602", priceNum: 6602, priceJPY: "¥7.7M",
    name: "Cozy Akiya in Kashiwazaki, Niigata",
    city: "Kashiwazaki", prefecture: "Niigata", region: "Chubu",
    beds: 7, size: "3,195", built: "1974", parking: "2 spots",
    notes: "7DK with exceptional square footage near Sea of Japan.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["coastal", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-5-bedroom-countryside-hideaway-in-ishize",
    price: "$23987", priceNum: 23987, priceJPY: "¥28M",
    name: "Traditional 5-Bedroom Countryside Hideaway in Ishize",
    city: "Ishize", prefecture: "Toyama", region: "Chubu",
    beds: 5, size: "1,181", built: "1977", parking: "1 spot",
    notes: "5DK traditional home in picturesque countryside setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-1-bedroom-village-escape-in-soyama",
    price: "$18667", priceNum: 18667, priceJPY: "¥22M",
    name: "Charming 1-Bedroom Village Escape in Soyama",
    city: "Soyama", prefecture: "Toyama", region: "Chubu",
    beds: 1, size: "495", built: "2006", parking: "0 spots",
    notes: "1LDK village escape with modern elements in Toyama.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-4-bedroom-countryside-hideaway-in-okamicho",
    price: "$56667", priceNum: 56667, priceJPY: "¥66M",
    name: "Vintage 4-Bedroom Countryside Hideaway in Okamicho",
    city: "Okamicho", prefecture: "Ibaraki", region: "Kanto",
    beds: 4, size: "1,181", built: "1973", parking: "0 spots",
    notes: "4-bedroom classic home in Ibaraki countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "restoration-ready-2-bedroom-cultural-gem-in-koya-garden",
    price: "$54086", priceNum: 54086, priceJPY: "¥63M",
    name: "Restoration-Ready 2-Bedroom Cultural Gem in Koya",
    city: "Koya", prefecture: "Ibaraki", region: "Kanto",
    beds: 2, size: "925", built: "2004", parking: "1 spot",
    notes: "2LDK restoration-ready home in Ibaraki with garden.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-3-bedroom-mountain-view-home-in-mae",
    price: "$45333", priceNum: 45333, priceJPY: "¥53M",
    name: "Tranquil 3-Bedroom Mountain View Home in Mae",
    city: "Mae", prefecture: "Ibaraki", region: "Kanto",
    beds: 3, size: "936", built: "1978", parking: "1 spot",
    notes: "3LDK mountain view home in peaceful Ibaraki.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-3-bedroom-rustic-getaway-in-mae",
    price: "$46602", priceNum: 46602, priceJPY: "¥54M",
    name: "Vintage 3-Bedroom Rustic Getaway in Mae",
    city: "Mae", prefecture: "Ibaraki", region: "Kanto",
    beds: 3, size: "936", built: "1978", parking: "0 spots",
    notes: "3LDK vintage property in rural Ibaraki area.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-5-bedroom-countryside-hideaway-in-kamigo",
    price: "$41119", priceNum: 41119, priceJPY: "¥48M",
    name: "Vintage 5-Bedroom Countryside Hideaway in Kamigo",
    city: "Kamigo", prefecture: "Ibaraki", region: "Kanto",
    beds: 5, size: "1,045", built: "1984", parking: "1 spot",
    notes: "5DK spacious home in Ibaraki countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "cozy-3-bedroom-village-escape-in-iijima",
    price: "$38667", priceNum: 38667, priceJPY: "¥45M",
    name: "Cozy 3-Bedroom Village Escape in Iijima",
    city: "Iijima", prefecture: "Ibaraki", region: "Kanto",
    beds: 3, size: "517", built: "1990", parking: "1 spot",
    notes: "3DK village property with character in Ibaraki.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-5-bedroom-cultural-gem-in-mayumi-town",
    price: "$21333", priceNum: 21333, priceJPY: "¥25M",
    name: "Traditional 5-Bedroom Cultural Gem in Mayumi Town",
    city: "Mayumi", prefecture: "Ibaraki", region: "Kanto",
    beds: 5, size: "1,325", built: "1987", parking: "2 spots",
    notes: "5DK classic home with traditional charm and stable bones.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "https://www.oldhousesjapan.com/properties-2/historic-5-bedroom-mountain-view-home-in-oaza-shimana",
    price: "$20000", priceNum: 20000, priceJPY: "¥23M",
    name: "Historic 5-Bedroom Mountain View Home in Oaza Shimana",
    city: "Shimana", prefecture: "Ibaraki", region: "Kanto",
    beds: 5, size: "1,061", built: "1983", parking: "2 spots",
    notes: "5DK countryside gem ready for restoration.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-6-bedroom-japanese-house-in-mikanoharamachi-2-chome",
    price: "$26667", priceNum: 26667, priceJPY: "¥31M",
    name: "Idyllic 6-Bedroom Japanese House in Mikanoharamachi 2-chome",
    city: "Mikanoharamachi", prefecture: "Ibaraki", region: "Kanto",
    beds: 6, size: "1,290", built: "1976", parking: "1 spot",
    notes: "6SDK spacious home in authentic countryside setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "peaceful-3-bedroom-countryside-hideaway-in-kohata",
    price: "$67847", priceNum: 67847, priceJPY: "¥79M",
    name: "Peaceful 3-Bedroom Countryside Hideaway in Kohata",
    city: "Kohata", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "918", built: "1995", parking: "1 spot",
    notes: "3LDK peaceful retreat in Kyoto countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "historic-2-bedroom-village-escape-in-uharashita",
    price: "$41171", priceNum: 41171, priceJPY: "¥48M",
    name: "Historic 2-Bedroom Village Escape in Uharashita",
    city: "Uharashita", prefecture: "Kyoto", region: "Kansai",
    beds: 2, size: "535", built: "1995", parking: "1 spot",
    notes: "2-bedroom village property with historic charm.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-3-bedroom-akiya-retreat-in-ogura-town",
    price: "$47287", priceNum: 47287, priceJPY: "¥55M",
    name: "Charming 3-Bedroom Akiya Retreat in Ogura Town",
    city: "Ogura", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "603", built: "1972", parking: "1 spot",
    notes: "3DK charming akiya ready for restoration.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-4-bedroom-cultural-gem-in-hironocho",
    price: "$57566", priceNum: 57566, priceJPY: "¥67M",
    name: "Tranquil 4-Bedroom Cultural Gem in Hironocho",
    city: "Hironocho", prefecture: "Kyoto", region: "Kansai",
    beds: 4, size: "861", built: "1989", parking: "1 spot",
    notes: "4DK traditional home in quiet Kyoto neighborhood.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-akiya-in-hofu",
    price: "$31890", priceNum: 31890, priceJPY: "¥37M",
    name: "Charming Akiya in Hōfu",
    city: "Hofu", prefecture: "Yamaguchi", region: "Chugoku",
    beds: 6, size: "1,080", built: "1971", parking: "0 spots",
    notes: "6DK traditional home with tatami rooms and cultural sites nearby.",
    isPremium: true, contact: "contact@oldhousesjapan.comOld Houses Japan",
    tags: ["yamaguchi", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "peaceful-4-bedroom-rustic-getaway-in-shinjocho",
    price: "$98667", priceNum: 98667, priceJPY: "¥115M",
    name: "Peaceful 4-Bedroom Rustic Getaway in Shinjocho",
    city: "Shinjocho", prefecture: "Toyama", region: "Chubu",
    beds: 4, size: "1,365", built: "1996", parking: "1 spot",
    notes: "4LDK+Storeroom countryside retreat in Toyama.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "peaceful-5-bedroom-village-escape-in-araya",
    price: "$92518", priceNum: 92518, priceJPY: "¥108M",
    name: "Peaceful 5-Bedroom Village Escape in Araya",
    city: "Araya", prefecture: "Toyama", region: "Chubu",
    beds: 5, size: "1,508", built: "2003", parking: "1 spot",
    notes: "5-bedroom rural property in charming Toyama.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-6-bedroom-cultural-gem-in-kojima",
    price: "$77333", priceNum: 77333, priceJPY: "¥90M",
    name: "Vintage 6-Bedroom Cultural Gem in Kojima",
    city: "Kojima", prefecture: "Toyama", region: "Chubu",
    beds: 6, size: "1,257", built: "1978", parking: "0 spots",
    notes: "Spacious 6-bedroom traditional home in Toyama countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "historic-5-bedroom-akiya-retreat-in-fujiki",
    price: "$67847", priceNum: 67847, priceJPY: "¥79M",
    name: "Historic 5-Bedroom Akiya Retreat in Fujiki",
    city: "Fujiki", prefecture: "Toyama", region: "Chubu",
    beds: 5, size: "971", built: "1981", parking: "2 spots",
    notes: "Spacious akiya with tatami rooms and traditional charm near mountains.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-5-bedroom-village-escape-in-awashimacho-2-chome",
    price: "$78667", priceNum: 78667, priceJPY: "¥92M",
    name: "Idyllic 5-Bedroom Village Escape in Awashimacho 2-chome",
    city: "Awashimacho", prefecture: "Toyama", region: "Chubu",
    beds: 5, size: "1,459", built: "1971", parking: "1 spot",
    notes: "Classic Japanese living in serene Toyama setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-3-bedroom-cultural-gem-in-arakawa",
    price: "$60994", priceNum: 60994, priceJPY: "¥71M",
    name: "Idyllic 3-Bedroom Cultural Gem in Arakawa",
    city: "Arakawa", prefecture: "Toyama", region: "Chubu",
    beds: 3, size: "695", built: "2001", parking: "0 spots",
    notes: "3LDK traditional home in peaceful Toyama countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-8-bedroom-countryside-hideaway-in-kizu",
    price: "$54826", priceNum: 54826, priceJPY: "¥64M",
    name: "Vintage 8-Bedroom Countryside Hideaway in Kizu",
    city: "Kizu", prefecture: "Toyama", region: "Chubu",
    beds: 8, size: "1,908", built: "1969", parking: "0 spots",
    notes: "8DK vintage gem with extensive living space near mountains.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-4-bedroom-village-escape-in-kamikuroda",
    price: "$30840", priceNum: 30840, priceJPY: "¥36M",
    name: "Vintage 4-Bedroom Village Escape in Kamikuroda",
    city: "Kamikuroda", prefecture: "Toyama", region: "Chubu",
    beds: 4, size: "1,039", built: "1972", parking: "0 spots",
    notes: "4LK village property with vintage charm in Toyama.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-5-bedroom-mountain-view-home-in-nakagawa-honmachi",
    price: "$5876", priceNum: 5876, priceJPY: "¥6.9M",
    name: "Tranquil 5-Bedroom Mountain View Home in Nakagawa Honmachi",
    city: "Nakagawa", prefecture: "Toyama", region: "Chubu",
    beds: 5, size: "640", built: "1964", parking: "0 spots",
    notes: "5K traditional home with mountain views in Toyama.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "7dk-home-in-tane-higashiomi",
    price: "$31051", priceNum: 31051, priceJPY: "¥36.5M",
    name: "7DK Home in Tane, Higashiomi",
    city: "Tane", prefecture: "Shiga", region: "Kansai",
    beds: 7, size: "1,995", built: "1976", parking: "Yes",
    notes: "Spacious traditional layout with garden and garage potential for renovation.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "garden", "shiga", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "4dk-home-in-nara-city-nara",
    price: "$32575", priceNum: 32575, priceJPY: "¥3.8M",
    name: "4DK Home in Nara City, Nara",
    city: "Nara", prefecture: "Nara", region: "Kansai",
    beds: 4, size: "941", built: "1969", parking: "1 spot",
    notes: "Traditional wooden structure with tatami rooms. Close to schools and local amenities.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nara"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "restoration-ready-3-bedroom-countryside-hideaway-in-higashino-butaicho",
    price: "$33267", priceNum: 33267, priceJPY: "¥39M",
    name: "Restoration-Ready 3-Bedroom Countryside Hideaway in Higashino Butaicho",
    city: "Higashino", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "494", built: "1974", parking: "0 spots",
    notes: "3-bedroom restoration-ready home in Kyoto.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "peaceful-1-bedroom-village-escape-in-yawata-nakanoyama",
    price: "$25333", priceNum: 25333, priceJPY: "¥30M",
    name: "Peaceful 1-Bedroom Village Escape in Yawata Nakanoyama",
    city: "Yawata", prefecture: "Kyoto", region: "Kansai",
    beds: 1, size: "549", built: "1976", parking: "0 spots",
    notes: "1LDK village property with peaceful setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-4-bedroom-akiya-retreat-in-kyoto-city",
    price: "$28000", priceNum: 28000, priceJPY: "¥33M",
    name: "Idyllic 4-Bedroom Akiya Retreat in Kyoto City",
    city: "Kyoto", prefecture: "Kyoto", region: "Kansai",
    beds: 4, size: "666", built: "1963", parking: "0 spots",
    notes: "4DK akiya ready for transformation in Kyoto.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-4-bedroom-cultural-gem-in-kyoto-city",
    price: "$26533", priceNum: 26533, priceJPY: "¥31M",
    name: "Idyllic 4-Bedroom Cultural Gem in Kyoto City",
    city: "Kyoto", prefecture: "Kyoto", region: "Kansai",
    beds: 4, size: "446", built: "1965", parking: "0 spots",
    notes: "4K compact cultural gem in Kyoto City.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "historic-3-bedroom-mountain-view-home-in-kyoto-city",
    price: "$31300", priceNum: 31300, priceJPY: "¥37M",
    name: "Historic 3-Bedroom Mountain View Home in Kyoto City",
    city: "Kyoto", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "428", built: "1974", parking: "0 spots",
    notes: "3K mountain view home with historic appeal.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-3-bedroom-countryside-hideaway-in-kyoto-city",
    price: "$30667", priceNum: 30667, priceJPY: "¥36M",
    name: "Traditional 3-Bedroom Countryside Hideaway in Kyoto City",
    city: "Kyoto", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "547", built: "1984", parking: "0 spots",
    notes: "3LDK traditional home in serene Kyoto setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "restoration-ready-8-bedroom-cultural-gem-in-yosano-cho",
    price: "$32000", priceNum: 32000, priceJPY: "¥37M",
    name: "Restoration-Ready 8-Bedroom Cultural Gem in Yosano-cho",
    city: "Yosano", prefecture: "Kyoto", region: "Kansai",
    beds: 8, size: "2,727", built: "1965", parking: "1 spot",
    notes: "Spacious 8K traditional home with cultural significance.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-3-bedroom-cultural-gem-in-tachikawa",
    price: "$67161", priceNum: 67161, priceJPY: "¥79M",
    name: "Spacious 3-Bedroom Cultural Gem in Tachikawa",
    city: "Tachikawa", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "876", built: "1981", parking: "2 spots",
    notes: "3DK spacious home with cultural character.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-3-bedroom-rustic-getaway-in-yawata-komatsu",
    price: "$67161", priceNum: 67161, priceJPY: "¥79M",
    name: "Traditional 3-Bedroom Rustic Getaway in Yawata Komatsu",
    city: "Yawata", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "606", built: "1977", parking: "0 spots",
    notes: "3-bedroom traditional home in scenic Kyoto.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-6-bedroom-mountain-view-home-in-kizugawa-city",
    price: "$61610", priceNum: 61610, priceJPY: "¥72M",
    name: "Idyllic 6-Bedroom Mountain View Home in Kizugawa City",
    city: "Kizugawa", prefecture: "Kyoto", region: "Kansai",
    beds: 6, size: "775", built: "1976", parking: "0 spots",
    notes: "6DK mountain view home in peaceful Kyoto setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "kyoto", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-5-bedroom-modern-escape-in-kyoto-city",
    price: "$61105", priceNum: 61105, priceJPY: "¥71M",
    name: "Idyllic 5-Bedroom Modern Escape in Kyoto City",
    city: "Kyoto", prefecture: "Kyoto", region: "Kansai",
    beds: 5, size: "837", built: "1988", parking: "1 spot",
    notes: "5-bedroom modern akiya in central Kyoto.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-3-bedroom-mountain-view-home-in-nishi-kuzesato",
    price: "$61679", priceNum: 61679, priceJPY: "¥72M",
    name: "Idyllic 3-Bedroom Mountain View Home in Nishi Kuzesato",
    city: "Nishi Kuzesato", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "606", built: "1972", parking: "0 spots",
    notes: "3-bedroom mountain view home in Kyoto area.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "restoration-ready-3-bedroom-akiya-retreat-in-1116-1-mori",
    price: "$80868", priceNum: 80868, priceJPY: "¥95M",
    name: "Restoration-Ready 3-Bedroom Akiya Retreat in 1116-1 Mori",
    city: "Mori", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "915", built: "2001", parking: "1 spot",
    notes: "3LDK restoration-ready akiya in Kyoto area.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "historic-5-bedroom-countryside-hideaway-in-nishinokyo",
    price: "$74015", priceNum: 74015, priceJPY: "¥87M",
    name: "Historic 5-Bedroom Countryside Hideaway in Nishinokyo",
    city: "Nishinokyo", prefecture: "Kyoto", region: "Kansai",
    beds: 5, size: "1,163", built: "1989", parking: "1 spot",
    notes: "5-bedroom historic home in culturally rich Kyoto.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-tatami-filled-1-bedroom-akiya-surrounded-by-scenic-trails-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Charming Tatami-Filled 1-Bedroom Akiya Surrounded by Scenic Trails in Nagano",
    city: "Furumachi", prefecture: "Nagano", region: "Japan",
    beds: 1, size: "588", built: "1992", parking: "2 spots",
    notes: "1DK charming akiya with tatami rooms in scenic area.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nagano"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-4-bedroom-akiya-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Charming 4-Bedroom Akiya in Nagano",
    city: "Chikuma", prefecture: "Nagano", region: "Japan",
    beds: 4, size: "391", built: "1953", parking: "2 spots",
    notes: "4DK compact akiya with traditional charm.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nagano"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "mountain-1-bedroom-akiya-near-hot-springs-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Mountain 1-Bedroom Akiya Near Hot Springs in Nagano",
    city: "Saku", prefecture: "Nagano", region: "Japan",
    beds: 1, size: "548", built: "1989", parking: "2 spots",
    notes: "1DK mountain akiya near onsen with cultural richness.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "nagano"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-forest-edge-5-bedroom-akiya-with-spacious-interiors-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Tranquil Forest-Edge 5-Bedroom Akiya with Spacious Interiors in Nagano",
    city: "Ueda", prefecture: "Nagano", region: "Japan",
    beds: 5, size: "996", built: "Unknown", parking: "2 spots",
    notes: "5DK spacious forest akiya in serene setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nagano", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "secluded-hillside-2-bedroom-akiya-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Secluded Hillside 2-Bedroom Akiya in Nagano",
    city: "Komoro", prefecture: "Nagano", region: "Japan",
    beds: 2, size: "579", built: "1996", parking: "1 spot",
    notes: "2DK secluded hillside retreat in Nagano.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nagano"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-4-bedroom-akiya-surrounded-by-scenic-trails-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Vintage 4-Bedroom Akiya Surrounded by Scenic Trails in Nagano",
    city: "Nagano", prefecture: "Nagano", region: "Japan",
    beds: 4, size: "1,149", built: "Unknown", parking: "0 spots",
    notes: "4DK unique akiya blending rural lifestyle and authentic Japanese charm.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nagano"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-7-bedroom-akiya-in-a-serene-neighborhood-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Tranquil 7-Bedroom Akiya in a Serene Neighborhod in Nagano",
    city: "Minamimaki", prefecture: "Nagano", region: "Japan",
    beds: 7, size: "1,285", built: "1970", parking: "1 spot",
    notes: "7DK serene village akiya in Japan Alps area.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nagano", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-forest-edge-4-bedroom-akiya-with-spacious-interiors-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Tranquil Forest-Edge 4-Bedroom Akiya with Spacious Interiors in Nagano",
    city: "Chikuma", prefecture: "Nagano", region: "Japan",
    beds: 4, size: "898", built: "1962", parking: "2 spots",
    notes: "4DK forest akiya with spacious countryside interiors.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["nagano"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "historic-mountain-8-bedroom-akiya-perfect-for-renovation-in-nagano",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Historic Mountain 8-Bedroom Akiya Perfect for Renovation in Nagano",
    city: "Ueda", prefecture: "Nagano", region: "Japan",
    beds: 8, size: "1,682", built: "1967", parking: "0 spots",
    notes: "8DK historic mountain akiya with renovation potential.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "mountain", "nagano", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "secluded-modern-house-in-hosono",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Secluded Modern House in Hosono",
    city: "Hosono", prefecture: "Fukui", region: "Chubu",
    beds: 7, size: "2,326", built: "1976", parking: "1 spot",
    notes: "7DK secluded modern akiya with historic architecture.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["fukui", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "serene-renovation-ready-home-in-gamo-town",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Serene Renovation-Ready Home in Gamo Town",
    city: "Gamo", prefecture: "Fukui", region: "Chubu",
    beds: 6, size: "1,938", built: "1970", parking: "0 spots",
    notes: "6DK serene home with traditional design in Fukui.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["fukui", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "historic-scenic-home-in-nanjo-district",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Historic Scenic Home in Nanjo District",
    city: "Nanjo", prefecture: "Fukui", region: "Chubu",
    beds: 7, size: "1,814", built: "1993", parking: "2 spots",
    notes: "7DK scenic home in historic Fukui district.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["fukui", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "secluded-scenic-home-in-obama-city-shimotakehara",
    price: "$18750", priceNum: 18750, priceJPY: "¥22M",
    name: "Secluded Scenic Home in Obama City Shimotakehara",
    city: "Obama", prefecture: "Fukui", region: "Chubu",
    beds: 4, size: "662", built: "1968", parking: "0 spots",
    notes: "4DK secluded scenic property in coastal Fukui.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["coastal", "fukui"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
];

export function getListing(slug: string): Listing | undefined {
  return listings.find((l) => l.slug === slug);
}

export function getFreeListing(): Listing[] {
  return listings.filter((l) => !l.isPremium).slice(0, 6);
}
