// New listings from Old Houses Japan (50 properties under $50k USD)
// Generated: 2026-03-21

  {
    slug: "spacious-3ldk-home-on-a-large-lot-in-sorachi-district",
    price: "$640", priceNum: 640, priceJPY: "¥750K",
    name: "Spacious 3LDK Home on a Large Lot in Sorachi District",
    city: "Kamisunagawachō", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "1,989", built: "1961", parking: "1 spot",
    notes: "Affordable entry-level Hokkaido property. Large lot with quiet residential feel near Sunagawa City. Easy access to shops and schools.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "classic-4ldk-home-in-otaru",
    price: "$5122", priceNum: 5122, priceJPY: "¥6M",
    name: "Classic 4LDK Home in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,208", built: "1900", parking: "1 spot",
    notes: "Peaceful Hokkaido living in quiet residential neighborhood. Close to city conveniences and local amenities.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "budget-4ldk-house-in-otaru",
    price: "$5122", priceNum: 5122, priceJPY: "¥6M",
    name: "Budget 4LDK House in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "875", built: "1964", parking: "0 spots",
    notes: "Rare affordable entry point into Hokkaido real estate. Potential for renovation into home or rental property with character.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "wooden-home-in-coastal-muroran",
    price: "$1921", priceNum: 1921, priceJPY: "¥2.3M",
    name: "Wooden Home in Coastal Muroran",
    city: "Muroran", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "811", built: "1976", parking: "0 spots",
    notes: "Diamond-in-the-rough coastal akiya market property. Traditional wooden home with renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "coastal", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "two-story-home-in-iwamizawa-hokkaido",
    price: "$5752", priceNum: 5752, priceJPY: "¥6.8M",
    name: "Two-Story Home in Iwamizawa, Hokkaido",
    city: "Iwamizawa", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,073", built: "1975", parking: "2 spots",
    notes: "Spacious two-story home with parking. Hokkaido countryside living near local amenities.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "3ldk-home-with-garden-parking-in-otaru",
    price: "$1281", priceNum: 1281, priceJPY: "¥1.5M",
    name: "3LDK Home With Garden & Parking in Otaru",
    city: "Otaru", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 3, size: "1,024", built: "1966", parking: "1 spot",
    notes: "Charming Sakura neighborhood property. Quiet area with easy access to shops. Garden and parking included.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "affordable-two-story-home-near-takikawa-station",
    price: "$6338", priceNum: 6338, priceJPY: "¥7.5M",
    name: "Affordable Two-Story Home Near Takikawa Station",
    city: "Takikawa", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "1,025", built: "1973", parking: "0 spots",
    notes: "Walk to train station. Full ownership. Two-story home with convenience and transit access.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "3dk-single-story-home-in-kitahara",
    price: "$6500", priceNum: 6500, priceJPY: "¥7.6M",
    name: "3DK Single-Story Home in Kitahara",
    city: "Kitahara", prefecture: "Fukushima", region: "Tohoku",
    beds: 3, size: "NA", built: "1955", parking: "1 spot",
    notes: "Budget-friendly akiya in Fukushima. Single-story traditional layout with renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "fukushima"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "6dk-home-in-kamijo-kashiwazaki-city-niigata",
    price: "$2957", priceNum: 2957, priceJPY: "¥3.5M",
    name: "6DK Home in Kamijo, Kashiwazaki City, Niigata",
    city: "Kashiwazaki", prefecture: "Niigata", region: "Chubu",
    beds: 6, size: "2,277", built: "1936", parking: "1 spot",
    notes: "Spacious wooden home with garden. Historic 1936 build. Significant renovation potential on large lot.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "garden", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-home-in-seiyo-ehime",
    price: "$2036", priceNum: 2036, priceJPY: "¥2.4M",
    name: "Charming Home in Seiyo, Ehime",
    city: "Seiyo", prefecture: "Ehime", region: "Shikoku",
    beds: 2, size: "676", built: "1975", parking: "0 spots",
    notes: "Traditional 4DK with tatami rooms and shoji doors. Quiet residential area in western Ehime. Renovation potential throughout.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "ehime"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-home-in-sasebo-nagasaki",
    price: "$68", priceNum: 68, priceJPY: "¥80K",
    name: "Traditional Home in Sasebo, Nagasaki",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 4, size: "649", built: "Unknown", parking: "0 spots",
    notes: "Traditional 4DK with tatami rooms and renovation potential in quiet residential neighborhood.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "3ldk-home-in-hakodate-hokkaido",
    price: "$69", priceNum: 69, priceJPY: "¥80K",
    name: "3LDK Home in Hakodate, Hokkaido",
    city: "Hakodate", prefecture: "Hokkaido", region: "Hokkaido",
    beds: 4, size: "682", built: "1969", parking: "0 spots",
    notes: "Charming akiya in quiet residential area. Ideal for renovation with traditional features and convenient access to local amenities.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "hokkaido"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "5k-home-in-nagasaki-city",
    price: "$6651", priceNum: 6651, priceJPY: "¥7.8M",
    name: "5K Home in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 5, size: "962", built: "1967", parking: "0 spots",
    notes: "Traditional 5DK with tatami rooms and shoji doors. Renovation potential in quiet residential neighborhood.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "nagasaki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "6dk-two-story-home-in-kosaka-kunimi-machi",
    price: "$11700", priceNum: 11700, priceJPY: "¥1.37M",
    name: "6DK Two-Story Home in Kosaka, Kunimi-machi",
    city: "Kunimi", prefecture: "Fukushima", region: "Tohoku",
    beds: 6, size: "1,755", built: "1979", parking: "1 spot",
    notes: "Sunny veranda with spacious garden and privacy near expressway. Classic Japanese countryside living.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "fukushima", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "cozy-3dk-countryside-home-in-koryocho-oike",
    price: "$16900", priceNum: 16900, priceJPY: "¥2M",
    name: "Cozy 3DK Countryside Home in Koryocho Oike",
    city: "Izumo", prefecture: "Shimane", region: "Chugoku",
    beds: 3, size: "1,066", built: "1983", parking: "0 spots",
    notes: "Single-story home near sea with garden and countryside charm. Izumo is known for cultural significance.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["coastal", "garden", "shimane"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-6dk-home-in-akikacho",
    price: "$12670", priceNum: 12670, priceJPY: "¥14.9M",
    name: "Traditional 6DK Home in Akikacho",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 6, size: "1,432", built: "1970", parking: "3 spots",
    notes: "Charming wooden home near Akikacho Station. Large lot with parking for 3+. Quiet and sunny.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "used-detached-house-in-takamicho",
    price: "$12900", priceNum: 12900, priceJPY: "¥1.98M",
    name: "Used Detached House in Takamicho",
    city: "Minamisoma", prefecture: "Fukushima", region: "Tohoku",
    beds: 6, size: "1,429", built: "1980", parking: "2 spots",
    notes: "2-story wooden house 2km from Haranomachi Station with sunlight and parking on Fukushima coast.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["fukushima", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "4dk-home-in-tane",
    price: "$3312", priceNum: 3312, priceJPY: "¥3.9M",
    name: "4DK Home in Tane",
    city: "Tane", prefecture: "Ehime", region: "Shikoku",
    beds: 4, size: "1,158", built: "1975", parking: "2 spots",
    notes: "Spacious layout with wooden interiors and renovation potential. Ideal for rural living in Japan.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "ehime"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-akiya-in-joetsu-niigata",
    price: "$2700", priceNum: 2700, priceJPY: "¥3.2M",
    name: "Spacious 5-Bedroom Akiya in Joetsu",
    city: "Joetsu", prefecture: "Niigata", region: "Chubu",
    beds: 5, size: "1,274", built: "1978", parking: "1 spot",
    notes: "Tatami rooms and traditional charm near mountains and sea. Gateway to Myoko and Hakuba ski resorts.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["coastal", "mountain", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "500. Toyama ranked #1 in Japan for quality of life. Traditional Japanese countryside layout.",
    price: "$3427", priceNum: 3427, priceJPY: "¥4M",
    name: "7-Bedroom Village Escape in Imizu",
    city: "Imizu", prefecture: "Toyama", region: "Chubu",
    beds: 7, size: "1,275", built: "1971", parking: "0 spots",
    notes: "7 bedrooms for under $3",
    isPremium: false, contact: "https://www.oldhousesjapan.com/properties-2/charming-7-bedroom-village-escape-in-imizu-honmachi-3-chome",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "ebino-hillside-hideaway",
    price: "$4560", priceNum: 4560, priceJPY: "¥5.3M",
    name: "Ebino Hillside Hideaway",
    city: "Ebino", prefecture: "Miyazaki", region: "Kyushu",
    beds: 3, size: "896", built: "1975", parking: "1 spot",
    notes: "5DK surrounded by nature with large yard and mountain views near Kirishima National Park.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "miyazaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "hillside-hideaway-in-nagasaki-city",
    price: "$5551", priceNum: 5551, priceJPY: "¥6.5M",
    name: "Hillside Hideaway in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 5, size: "1,139", built: "1967", parking: "0 spots",
    notes: "4DK traditional home with mountain views and renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "mountain", "nagasaki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "matsue-city-garden-view-akiya",
    price: "$10410", priceNum: 10410, priceJPY: "¥12M",
    name: "Matsue City Garden-View Akiya",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 5, size: "973", built: "1970", parking: "0 spots",
    notes: "5DK akiya with yard and detached structure in charming water city.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "shimane-starter-akiya-in-matsue-city",
    price: "$17350", priceNum: 17350, priceJPY: "¥20M",
    name: "Shimane Starter Akiya in Matsue City",
    city: "Matsue", prefecture: "Shimane", region: "Chugoku",
    beds: 6, size: "1,200", built: "1976", parking: "0 spots",
    notes: "6K affordable fixer-upper in scenic Matsue.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["shimane", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "6dk-home-in-saijo-city-ehime",
    price: "$7590", priceNum: 7590, priceJPY: "¥8.9M",
    name: "6DK Home in Saijo City",
    city: "Saijo", prefecture: "Ehime", region: "Shikoku",
    beds: 6, size: "1,919", built: "1991", parking: "1 spot",
    notes: "One of newer builds (1991). Spacious 6-bedroom layout with garden. Known for pure groundwater and traditional festivals.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "ehime", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-4-bedroom-akiya-retreat-in-shiomigaoka-4-chome",
    price: "$32000", priceNum: 32000, priceJPY: "¥37M",
    name: "Traditional 4-Bedroom Akiya Retreat in Shiomigaoka 4-chome",
    city: "Shiomigaoka", prefecture: "Ibaraki", region: "Kanto",
    beds: 4, size: "891", built: "1980", parking: "1 spot",
    notes: "4DK traditional akiya with renovation potential.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-2-bedroom-countryside-hideaway-in-kumiage",
    price: "$20000", priceNum: 20000, priceJPY: "¥23M",
    name: "Spacious 2-Bedroom Countryside Hideaway in Kumiage",
    city: "Kumiage", prefecture: "Ibaraki", region: "Kanto",
    beds: 2, size: "538", built: "1987", parking: "1 spot",
    notes: "2-bedroom rural property with countryside charm.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-4-bedroom-country-home-in-sunazawacho",
    price: "$13333", priceNum: 13333, priceJPY: "¥15M",
    name: "Tranquil 4-Bedroom Country Home in Sunazawacho",
    city: "Sunazawacho", prefecture: "Ibaraki", region: "Kanto",
    beds: 4, size: "980", built: "1993", parking: "1 spot",
    notes: "4K country property with modern updates.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-home-in-nagasaki-city",
    price: "$3370", priceNum: 3370, priceJPY: "¥3.9M",
    name: "Traditional Home in Nagasaki City",
    city: "Nagasaki", prefecture: "Nagasaki", region: "Kyushu",
    beds: 4, size: "598", built: "1968", parking: "0 spots",
    notes: "4DK traditional akiya with tatami rooms in culturally rich city.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "akiya-in-sasebo-nagasaki",
    price: "$2695", priceNum: 2695, priceJPY: "¥3.2M",
    name: "Akiya in Sasebo, Nagasaki",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 3, size: "637", built: "1900", parking: "0 spots",
    notes: "3-bedroom affordable akiya with charm and renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "nagasaki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "affordable-6dk-home-with-bay-views-in-sasebo-city",
    price: "$6245", priceNum: 6245, priceJPY: "¥7.3M",
    name: "Affordable 6DK Home with Bay Views in Sasebo City",
    city: "Sasebo", prefecture: "Nagasaki", region: "Kyushu",
    beds: 6, size: "1,303", built: "1967", parking: "0 spots",
    notes: "6DK akiya with coastal bay views and renovation potential.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["renovation-project", "coastal", "nagasaki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "spacious-7-bedroom-cultural-gem-in-tate",
    price: "$6854", priceNum: 6854, priceJPY: "¥8M",
    name: "Spacious 7-Bedroom Cultural Gem in Tate",
    city: "Tate", prefecture: "Toyama", region: "Chubu",
    beds: 7, size: "1,698", built: "1969", parking: "1 spot",
    notes: "Spacious 7DK traditional home in rural Toyama.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "cozy-akiya-in-kashiwazaki-niigata",
    price: "$6602", priceNum: 6602, priceJPY: "¥7.7M",
    name: "Cozy Akiya in Kashiwazaki, Niigata",
    city: "Kashiwazaki", prefecture: "Niigata", region: "Chubu",
    beds: 7, size: "3,195", built: "1974", parking: "2 spots",
    notes: "7DK with exceptional square footage near Sea of Japan.",
    isPremium: false, contact: "contact@oldhousesjapan.com",
    tags: ["coastal", "niigata", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-5-bedroom-countryside-hideaway-in-ishize",
    price: "$23987", priceNum: 23987, priceJPY: "¥28M",
    name: "Traditional 5-Bedroom Countryside Hideaway in Ishize",
    city: "Ishize", prefecture: "Toyama", region: "Chubu",
    beds: 5, size: "1,181", built: "1977", parking: "1 spot",
    notes: "5DK traditional home in picturesque countryside setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-1-bedroom-village-escape-in-soyama",
    price: "$18667", priceNum: 18667, priceJPY: "¥22M",
    name: "Charming 1-Bedroom Village Escape in Soyama",
    city: "Soyama", prefecture: "Toyama", region: "Chubu",
    beds: 1, size: "495", built: "2006", parking: "0 spots",
    notes: "1LDK village escape with modern elements in Toyama.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-4-bedroom-countryside-hideaway-in-okamicho",
    price: "$56667", priceNum: 56667, priceJPY: "¥66M",
    name: "Vintage 4-Bedroom Countryside Hideaway in Okamicho",
    city: "Okamicho", prefecture: "Ibaraki", region: "Kanto",
    beds: 4, size: "1,181", built: "1973", parking: "0 spots",
    notes: "4-bedroom classic home in Ibaraki countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "restoration-ready-2-bedroom-cultural-gem-in-koya-garden",
    price: "$54086", priceNum: 54086, priceJPY: "¥63M",
    name: "Restoration-Ready 2-Bedroom Cultural Gem in Koya",
    city: "Koya", prefecture: "Ibaraki", region: "Kanto",
    beds: 2, size: "925", built: "2004", parking: "1 spot",
    notes: "2LDK restoration-ready home in Ibaraki with garden.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["garden", "ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-3-bedroom-mountain-view-home-in-mae",
    price: "$45333", priceNum: 45333, priceJPY: "¥53M",
    name: "Tranquil 3-Bedroom Mountain View Home in Mae",
    city: "Mae", prefecture: "Ibaraki", region: "Kanto",
    beds: 3, size: "936", built: "1978", parking: "1 spot",
    notes: "3LDK mountain view home in peaceful Ibaraki.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["mountain", "ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-3-bedroom-rustic-getaway-in-mae",
    price: "$46602", priceNum: 46602, priceJPY: "¥54M",
    name: "Vintage 3-Bedroom Rustic Getaway in Mae",
    city: "Mae", prefecture: "Ibaraki", region: "Kanto",
    beds: 3, size: "936", built: "1978", parking: "0 spots",
    notes: "3LDK vintage property in rural Ibaraki area.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "vintage-5-bedroom-countryside-hideaway-in-kamigo",
    price: "$41119", priceNum: 41119, priceJPY: "¥48M",
    name: "Vintage 5-Bedroom Countryside Hideaway in Kamigo",
    city: "Kamigo", prefecture: "Ibaraki", region: "Kanto",
    beds: 5, size: "1,045", built: "1984", parking: "1 spot",
    notes: "5DK spacious home in Ibaraki countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "cozy-3-bedroom-village-escape-in-iijima",
    price: "$38667", priceNum: 38667, priceJPY: "¥45M",
    name: "Cozy 3-Bedroom Village Escape in Iijima",
    city: "Iijima", prefecture: "Ibaraki", region: "Kanto",
    beds: 3, size: "517", built: "1990", parking: "1 spot",
    notes: "3DK village property with character in Ibaraki.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "traditional-5-bedroom-cultural-gem-in-mayumi-town",
    price: "$21333", priceNum: 21333, priceJPY: "¥25M",
    name: "Traditional 5-Bedroom Cultural Gem in Mayumi Town",
    city: "Mayumi", prefecture: "Ibaraki", region: "Kanto",
    beds: 5, size: "1,325", built: "1987", parking: "2 spots",
    notes: "5DK classic home with traditional charm and stable bones.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "idyllic-6-bedroom-japanese-house-in-mikanoharamachi-2-chome",
    price: "$26667", priceNum: 26667, priceJPY: "¥31M",
    name: "Idyllic 6-Bedroom Japanese House in Mikanoharamachi 2-chome",
    city: "Mikanoharamachi", prefecture: "Ibaraki", region: "Kanto",
    beds: 6, size: "1,290", built: "1976", parking: "1 spot",
    notes: "6SDK spacious home in authentic countryside setting.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["ibaraki", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "peaceful-3-bedroom-countryside-hideaway-in-kohata",
    price: "$67847", priceNum: 67847, priceJPY: "¥79M",
    name: "Peaceful 3-Bedroom Countryside Hideaway in Kohata",
    city: "Kohata", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "918", built: "1995", parking: "1 spot",
    notes: "3LDK peaceful retreat in Kyoto countryside.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "historic-2-bedroom-village-escape-in-uharashita",
    price: "$41171", priceNum: 41171, priceJPY: "¥48M",
    name: "Historic 2-Bedroom Village Escape in Uharashita",
    city: "Uharashita", prefecture: "Kyoto", region: "Kansai",
    beds: 2, size: "535", built: "1995", parking: "1 spot",
    notes: "2-bedroom village property with historic charm.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-3-bedroom-akiya-retreat-in-ogura-town",
    price: "$47287", priceNum: 47287, priceJPY: "¥55M",
    name: "Charming 3-Bedroom Akiya Retreat in Ogura Town",
    city: "Ogura", prefecture: "Kyoto", region: "Kansai",
    beds: 3, size: "603", built: "1972", parking: "1 spot",
    notes: "3DK charming akiya ready for restoration.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "tranquil-4-bedroom-cultural-gem-in-hironocho",
    price: "$57566", priceNum: 57566, priceJPY: "¥67M",
    name: "Tranquil 4-Bedroom Cultural Gem in Hironocho",
    city: "Hironocho", prefecture: "Kyoto", region: "Kansai",
    beds: 4, size: "861", built: "1989", parking: "1 spot",
    notes: "4DK traditional home in quiet Kyoto neighborhood.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["kyoto"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "charming-akiya-in-hofu",
    price: "$31890", priceNum: 31890, priceJPY: "¥37M",
    name: "Charming Akiya in Hōfu",
    city: "Hofu", prefecture: "Yamaguchi", region: "Chugoku",
    beds: 6, size: "1,080", built: "1971", parking: "0 spots",
    notes: "6DK traditional home with tatami rooms and cultural sites nearby.",
    isPremium: true, contact: "contact@oldhousesjapan.comOld Houses Japan",
    tags: ["yamaguchi", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "peaceful-4-bedroom-rustic-getaway-in-shinjocho",
    price: "$98667", priceNum: 98667, priceJPY: "¥115M",
    name: "Peaceful 4-Bedroom Rustic Getaway in Shinjocho",
    city: "Shinjocho", prefecture: "Toyama", region: "Chubu",
    beds: 4, size: "1,365", built: "1996", parking: "1 spot",
    notes: "4LDK+Storeroom countryside retreat in Toyama.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
  {
    slug: "peaceful-5-bedroom-village-escape-in-araya",
    price: "$92518", priceNum: 92518, priceJPY: "¥108M",
    name: "Peaceful 5-Bedroom Village Escape in Araya",
    city: "Araya", prefecture: "Toyama", region: "Chubu",
    beds: 5, size: "1,508", built: "2003", parking: "1 spot",
    notes: "5-bedroom rural property in charming Toyama.",
    isPremium: true, contact: "contact@oldhousesjapan.com",
    tags: ["toyama", "spacious"],
    images: ["https://via.placeholder.com/400x300?text=Akiya"],
  },
];

export function getListing(slug: string): Listing | undefined {
  return listings.find((l) => l.slug === slug);
}

export function getFreeListing(): Listing[] {
  return listings.filter((l) => !l.isPremium).slice(0, 6);
}
